name: Pipeline CI/CD
run-name: ${{ github.actor }} run Actions 🚀
on:
  - push
  - workflow_dispatch

jobs:
  docker:
    uses: iran-mirror/gh-actions/.github/workflows/docker.yaml@main
    with:
      debug: true
      registry: ${{ vars.REGISTERY_ADDRESS }}
    secrets:
      REGISTERY_USER: ${{ github.actor }}
      REGISTERY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  argocd:
    uses: iran-mirror/gh-actions/.github/workflows/argocd.yaml@main
    needs: docker
    with:
      debug: true
      registry: ${{ vars.REGISTERY_ADDRESS }}
    secrets:
      ARGOCD_GIT_TOKEN: ${{ secrets.ARGOCD_GIT_TOKEN }}
